version: "3.8"

services:

  app:
    build:
      context: .
    image: 'kain69/vkpost'
    container_name: VkPost
    ports:
      - "80:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=VkPost
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
#    external: true